Fix issues with applyMultiSignatures
HorizenOfficial/zencashjs pull request #28
Opened 2019-08-09 16:57 UTC by al73rna

* Fixed signatures overwriting each other if applied one at a time
* Fixed the order of signatures not being checked against redeemScript. signatures will now be sorted regardless of their initial order.

2019-08-09 18:20 UTC, nicolam1 commented on src/transaction.js
> +  var unmatched = JSON.parse(JSON.stringify(allSigs))
how come we are using a mix of es6 and regular js standards use const or let.

2019-08-09 18:21 UTC, nicolam1 commented on test/transaction.js
> +  var txObjSig1 = zencashjs.transaction.applyMultiSignatures(txobj, 0, [sig1], redeemScript)
const?

2019-08-09 18:22 UTC, nicolam1 commented
@cronicc do we have ci for this repo?

2019-08-09 20:41 UTC, cronicc commented
Yes, we do

2019-08-09 20:45 UTC, nicolam1 commented
for some reason the check is not reported then.

2019-08-09 20:47 UTC, cronicc commented
https://travis-ci.org/ZencashOfficial/zencashjs/builds/569927719?utm_source=github_status&utm_medium=notification

The repo still seems to be using the travis legacy open source integration. So it's running on travis.ci-org instead of travis-ci.com,

2019-08-10 02:03 UTC, al73rna commented
The pipeline was failing because I hadn't committed the output code as well. It's fixed now.

Also addressed your comments @nicolam1

2019-08-11 16:10 UTC, nicolam1 commented on src/transaction.js
> +  var txObj = JSON.parse(JSON.stringify(_txObj))
const

2019-08-11 18:45 UTC, al73rna commented on src/transaction.js
> +  var txObj = JSON.parse(JSON.stringify(_txObj))
done

2019-08-19 11:01 UTC, cronicc commented
Not a regression but an additional bug, zencashjs doesn't handle m-of-n multisig correctly if m=n.

2020-07-07 19:28 UTC, Rifat0000 commented
What

2020-08-26 17:50 UTC, brutuscat commented
Hi, I'm looking into multisig wallets for ZEN and this JS lib looks like a great programmatic way of using this feature. Are the issues reported above still relevant? Should use something else instead for ZEN MultiSig wallets?

2020-10-08 13:20 UTC, angievi commented
> Hi, I'm looking into multisig wallets for ZEN and this JS lib looks like a great programmatic way of using this feature. Are the issues reported above still relevant? Should use something else instead for ZEN MultiSig wallets?

This PR would extent the multisignature functionality of zencashjs, but even without this PR multisignature functionality works fine.

please take a look at the examples in https://github.com/HorizenOfficial/zencashjs/blob/master/README.md#example-usage-multi-sig

2022-01-04 16:05 UTC, QAWSED4455 requested changes
issue27/applyMultiSignatures-fix

2024-03-06 19:39 UTC, closed without merging